user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

ders:
    resource: "@DersBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"