<?php

namespace DersBundle\Repository;

/**
 * DersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DersRepository extends \Doctrine\ORM\EntityRepository
{
}
