<?php

namespace DersBundle\Repository;

/**
 * KonuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KonuRepository extends \Doctrine\ORM\EntityRepository
{
}
